### ISSUE TITLE
3 PRs

### ISSUE THREAD

**Issue by akesson** [tylerreisinger/prisma#21]
@tylerreisinger thanks for the prisma crate! I really prefer it compared to the alternatives.

I created three PRs that should be very clean and easy to merge. They don't touch any of the current features so no need to worry about regressions. 

Thanks

**Comment by tylerreisinger** [comment]
It's been a while, but I merged them. Sorry for the delay, I've been dealing with health issues and have not had much time to update my projects. Thanks for the PRs, they all seem good.

**Comment by akesson** [comment]
No worries for the delay, instead thank you for creating and maintaining this!
